export const courseLists = [
  {
    id: 1,
    slug: "advanced-digital-marketing-bootcamp",
    title: "Brand Developer",
    img: "/job-training/brand.png",
    duration: "5 months",
    price: "80000",
    originalPrice: "100000",
    includes: [
      "Psychology class",
      "Personality Development",
      "Life Books",
      "Personal Guidance",
      "Interview Practice",
      "Placement Opportunity",
    ],
  },
  {
    id: 2,
    slug: "full-stack-web-development-bootcamp",
    title: "Full Stack Web Developer",
    img: "/job-training/fullstack.png",
    duration: "5 months",
    price: "80000",
    originalPrice: "100000",
    includes: [
      "Psychology class",
      "Personality Development",
      "Life Books",
      "Personal Guidance",
      "Interview Practice",
      "Placement Opportunity",
    ],
  },
  {
    id: 3,
    slug: "digital-marketing-bootcamp",
    title: "Social Media Manager",
    img: "/job-training/social.png",
    duration: "5 months",
    price: "80000",
    originalPrice: "100000",
    includes: [
      "Psychology class",
      "Personality Development",
      "Life Books",
      "Personal Guidance",
      "Interview Practice",
      "Placement Opportunity",
    ],
  },
  {
    id: 4,
    slug: "graphic-designing-bootcamp",
    title: "Graphic Designer",
    img: "/job-training/graphic.png",
    duration: "3 months",
    price: "50000",
    originalPrice: "60000",
    includes: [
      "Psychology class",
      "Personality Development",
      "Life Books",
      "Portfolio Review",
      "Internship Guidance",
      "Placement Opportunity",
    ],
  },
  {
    id: 5,
    slug: "web-development-bootcamp",
    title: "Web Designer",
    img: "/job-training/webdev.png",
    duration: "3 months",
    price: "50000",
    originalPrice: "60000",
    includes: [
      "Psychology class",
      "Personality Development",
      "Life Books",
      "Personal Guidance",
      "Interview Practice",
      "Placement Opportunity",
    ],
  },
  {
    id: 6,
    slug: "creative-designer",
    title: "Creative Designer",
    img: "/job-training/sales.png",
    duration: "3 months",
    price: "50000",
    originalPrice: "60000",
    includes: [
      "Psychology class",
      "Personality Development",
      "Life Books",
      "Personal Guidance",
      "Interview Practice",
      "Placement Opportunity",
    ],
  },
];
